---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ssd-loki.ssd-loki.com
  resources:
  - ssdlokis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ssd-loki.ssd-loki.com
  resources:
  - ssdlokis/finalizers
  verbs:
  - update
- apiGroups:
  - ssd-loki.ssd-loki.com
  resources:
  - ssdlokis/status
  verbs:
  - get
  - patch
  - update
